#!/usr/bin/sh

# _                                          
#| |__    ___   _ __   __      __  _ __ ___  
#| '_ \  / __| | '_ \  \ \ /\ / / | '_ ` _ \ 
#| |_) | \__ \ | |_) |  \ V  V /  | | | | | |
#|_.__/  |___/ | .__/    \_/\_/   |_| |_| |_|
#              |_|                           
# Config by yeyee2901
# last edit: Dec 2021

bspc monitor -d   甆    ﭮ  

#### BSPWM configuration ####
bspc config border_radius                 8
bspc config border_width                  2
bspc config window_gap                    5
bspc config top_padding                   5
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#ee44bb"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

### BSPWM Window Rules ###
# sadly, bspwm rules doesn't have a straight forward
# way to match a pattern using regex
bspc rule -a kitty                      desktop='^1'
bspc rule -a Firefox                    desktop='^2'
bspc rule -a zoom                       desktop='^4'
bspc rule -a obs                        desktop='^4'
bspc rule -a Gimp                       desktop='^5'
bspc rule -a libreoffice-startcenter    desktop='^6'
bspc rule -a discord                    desktop='^7'
bspc rule -a Pavucontrol                desktop='^9'
bspc rule -a Nitrogen                   desktop='^9'
bspc rule -a Arandr                     desktop='^9'

## These windows will always be set to floating mode
bspc rule -a Thunar state=floating

# AUTOSTART
$HOME/.config/bspwm/autostart.sh
